import type { User } from "./types";

const mockUsers: User[] = [
  {
    id: "U001",
    first_name: "Alice",
    last_name: "Smith",
    name: "Alice Smith",
    role: "pharmacist",
    branch: "Main Branch",
    status: "active",
    image: "https://randomuser.me/api/portraits/women/68.jpg",
    email: "alice@veripharm.com",
    phone: "555-1234",
    salary: "2000",
  },
  {
    id: "U002",
    first_name: "Bob",
    last_name: "Brown",
    name: "Bob Brown",
    role: "cashier",
    branch: "Westside Branch",
    status: "inactive",
    image: "https://randomuser.me/api/portraits/men/65.jpg",
    email: "bob@veripharm.com",
    phone: "555-5678",
    salary: "1500",
  },
  {
    id: "U003",
    first_name: "Carlos",
    last_name: "Green",
    name: "Carlos Green",
    role: "manager",
    branch: "Eastside Branch",
    status: "active",
    image: "https://randomuser.me/api/portraits/men/66.jpg",
    email: "carlos@veripharm.com",
    phone: "555-8765",
    salary: "3000",
  },
  {
    id: "U004",
    first_name: "Diana",
    last_name: "White",
    name: "Diana White",
    role: "staff",
    branch: "Main Branch",
    status: "active",
    image: "https://randomuser.me/api/portraits/women/67.jpg",
    email: "diana@veripharm.com",
    phone: "555-4321",
    salary: "1200",
  },
  {
    id: "U005",
    first_name: "Evelyn",
    last_name: "Sales",
    name: "Evelyn Sales",
    role: "staff",
    branch: "Westside Branch",
    status: "active",
    image: "https://randomuser.me/api/portraits/women/69.jpg",
    email: "evelyn.sales@veripharm.com",
    phone: "555-9988",
    salary: "1800",
  },
  // New staff for Eastside Branch
  {
    id: "U006",
    first_name: "Frank",
    last_name: "East",
    name: "Frank East",
    role: "staff",
    branch: "Eastside Branch",
    status: "active",
    image: "https://randomuser.me/api/portraits/men/70.jpg",
    email: "frank.east@veripharm.com",
    phone: "555-1122",
    salary: "1750",
  },
  {
    id: "U007",
    first_name: "Grace",
    last_name: "Lin",
    name: "Grace Lin",
    role: "staff",
    branch: "Eastside Branch",
    status: "active",
    image: "https://randomuser.me/api/portraits/women/71.jpg",
    email: "grace.lin@veripharm.com",
    phone: "555-3344",
    salary: "1780",
  },
  // New staff for Westside Branch
  {
    id: "U008",
    first_name: "Henry",
    last_name: "West",
    name: "Henry West",
    role: "staff",
    branch: "Westside Branch",
    status: "active",
    image: "https://randomuser.me/api/portraits/men/72.jpg",
    email: "henry.west@veripharm.com",
    phone: "555-5566",
    salary: "1820",
  },
  {
    id: "U009",
    first_name: "Ivy",
    last_name: "Chen",
    name: "Ivy Chen",
    role: "staff",
    branch: "Westside Branch",
    status: "active",
    image: "https://randomuser.me/api/portraits/women/73.jpg",
    email: "ivy.chen@veripharm.com",
    phone: "555-7788",
    salary: "1790",
  },
  {
    id: "U010",
    first_name: "Jack",
    last_name: "Main",
    name: "Jack Main",
    role: "staff",
    branch: "Main Branch",
    status: "active",
    image: "https://randomuser.me/api/portraits/men/74.jpg",
    email: "jack.main@veripharm.com",
    phone: "555-8899",
    salary: "1850",
  },
  {
    id: "U011",
    first_name: "Karen",
    last_name: "Lee",
    name: "Karen Lee",
    role: "staff",
    branch: "Main Branch",
    status: "active",
    image: "https://randomuser.me/api/portraits/women/75.jpg",
    email: "karen.lee@veripharm.com",
    phone: "555-9900",
    salary: "1870",
  },
  {
    id: "U012",
    first_name: "Liam",
    last_name: "Turner",
    name: "Liam Turner",
    role: "staff",
    branch: "Main Branch",
    status: "active",
    image: "https://randomuser.me/api/portraits/men/76.jpg",
    email: "liam.turner@veripharm.com",
    phone: "555-2233",
    salary: "1860",
  },
];

export default mockUsers;
